### ISSUE TITLE
Forma de pago

### ISSUE THREAD

**Issue by leyvicaz** [fortiz/sat#2]
Buen día, estaba revisando tu librería para la generación de CFDI y encontré algo que me llamó la atención.

#"FormaPago"=>$arr['metodoDePago'],
#"MetodoPago"=>$arr['formaDePago'],

¿Porque en las lineas 146 y 147 del archivo satxmlsv33.php, están comentados estos atributos?

¿Ya no son necesario?
¿Se piden en otro lado?

Por cierto excelente trabajo.

**Comment by fortiz** [comment]
Muchas gracias.

Es un error histórico, cuando subí el archivo mi departamento de contabilidad dijo que todo lo opcional no lo pusiera. (este es el archivo real que va a usar la empresa cuando arranque, todavia seguimos en 3.2).

Ya con las nuevas guías de llenado y el archivo de preguntas frecuentes publicados por el SAT no hay duda, deben de ir.

En unos dias subo la nueva versión que va a incluir mas nodos como los cfdis relacionados.

Saludos
