### ISSUE TITLE
Validador de cfdi

### ISSUE THREAD

**Issue by VRTHOME** [fortiz/sat#3]
Hola Fernado, antes que nada muchas gracias por tus proyectos , en lo personal me ayudan a realizar correcciones en mi código y aun que no soy un na persona con mucha experiencia en estos desarrollos, me auxilia mucho tu validador con mis xml.. 
te comparto que el dia de hoy no esta funcionando el validador.. 
meto un xml 3.2 y no me arroja resultado , meto un 3.3 y el mensaje es.. "Sigue siendo utf8, usa decode"
de antemano muchas gracias.

**Comment by fortiz** [comment]
Gracias por el aviso, ya cambie la librería highlighter de pear por una javascript que si sirve en PHP7.

Saludos

**Comment by VRTHOME** [comment]
Muchas gracias...
