### ISSUE TITLE
satxmlsv33_genera_cadena_original

### ISSUE THREAD

**Issue by azamudio1971** [fortiz/sat#4]
como hago para her la cadena original??
me sale esto:

Call to a member function saveXML() on null

**Comment by fortiz** [comment]
¿supongo que te refieres a esta linea?

$paso->loadXML($xml->saveXML());

Ese error significa que $xml no contiene una objeto DOM valido.

¿quieres solo usar la función de satxmlsv33_genera_cadena_original() fuera de contexto o fue ejecutada dentro de todo  mi programa que primero crea el XML?

**Comment by azamudio1971** [comment]
la quiero utilizar fuera de contexto
