### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by Buitch** [fortiz/sat#6]
Hola Buen día de casualidad sabrás por que me arroja estos errores 
Warning: XSLTProcessor::transformToXml() [xsltprocessor.transformtoxml]: xsl:call-template: misplaced text element in E:\Facturacion33.php on line 171

Warning: XSLTProcessor::transformToXml() [xsltprocessor.transformtoxml]: xsl:call-template: misplaced text element in E:\Facturacion33.php on line 171

Warning: openssl_sign() [function.openssl-sign]: Unknown signature algorithm. in E:\Facturacion33.php on line 178

el tramo de codigo al que hace referncia es este 

163   private function get_cadena_original(){
164		$dom_xml_cadena	= new DOMDocument();
165		$dom_xml_cadena->loadXML($this->xml_factura->saveXML());
166		$xsltDoc = new DOMDocument();
167       $xsltDoc->load("cadenaoriginal.xslt");
168
169        $proc = new XSLTProcessor();
170        @$proc->importStylesheet($xsltDoc);
171        $cadena = $proc->transformToXML($dom_xml_cadena);
172
173		return $cadena;
174	}
175
176	private function get_sello_digital(){
177		$sello = null;
178		openssl_sign($this->get_cadena_original(), $sello, $this->arr_factura["factura"]["llave"] , 
                 OPENSSL_ALGO_SHA256);
179		return  base64_encode($sello);
180	}

**Comment by fortiz** [comment]
¿Que version de PHP tienes?

Nota:

Estas constantes fueron añadidas en la versión 5.4.8.

OPENSSL_ALGO_RMD160, OPENSSL_ALGO_SHA224, **OPENSSL_ALGO_SHA256**, OPENSSL_ALGO_SHA384, OPENSSL_ALGO_SHA512

**Comment by Buitch** [comment]
Hola BUen día, muchas gracias y en efecto el error que no mandaba era por que en el servidor estaba la version5.3, pero ahora me esta enviando el error de 

 El resultado de la digestión debe ser igual al resultado de la desencripción del sello. 
no se si tengas alguna idea de que es lo que este pasando?

Saludos y gracias.

**Comment by fortiz** [comment]
Lo mejor para esto es que me mandas tu XML a mi correo fernando.ortiz @ gmail . com para ver por donde es

**Comment by Buitch** [comment]
Listo ya te lo envié, gracias.
