### ISSUE TITLE
Empezando con SAT

### ISSUE THREAD

**Issue by BrianMoreno1994** [fortiz/sat#7]
Hola amigo, acabo de encontrar este repositorio. La verdad soy muy nuevo en esto de la generación de facturas. Mis preguntas son las siguientes:

> ¿Esta librería me sirven para generar facturas?
> ¿Qué necesito que tener para poder generar una factura? (PD. ya estoy registrado en SHCP)
> ¿Cuál es el proceso a seguir para generarlas?

Te agradecería infinitamente si pones un ejemplo de todo el proceso de facturación. ¡Muchas gracias y saludos!

**Comment by fortiz** [comment]
Hola, aqui tengo un poco mas explicado el proceso de la generacion http://www.lacorona.com.mx/fortiz/sat/#generacion

Pero definitivamente no es una librería con la que puedas facturar nada mas instalando, esta librería esta pensada para ser integrado a tu ERP y como cada paquete es diferente solo da las bases.

Lo que si tiene listo para funcionar es la validación,
